package webmarket;

/**
 * @author Simos
 */

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import model.Store;
import model.StoreProduct;
import model.Purchase;

public class AdminStore extends javax.swing.JFrame {

    private EntityManager em;
    private int selected;
    private Store tempStore;
    private Store deleteStore = new Store();
    
    
    
    
    /**
     * Creates new form AdminStore
     */
    
    public AdminStore() {
         EntityManagerFactory emf = Persistence.createEntityManagerFactory("WebMarketPU");
        // Δημιουργία του Entity Manager
        em = emf.createEntityManager();          
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        WebMarketPUEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("WebMarketPU").createEntityManager();
        storeQuery = java.beans.Beans.isDesignTime() ? null : WebMarketPUEntityManager0.createQuery("SELECT s FROM Store s \nWHERE s.storeId > 1");
        storeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(storeQuery.getResultList());
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        textField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WebMarket - Διαχείριση καταστημάτων (administrator)");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, storeList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(45);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Λίστα καταστημάτων");

        jButton1.setText("Νέο");

        jBtnEdit.setText("Τροποποίηση");
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Διαγραφή");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        ExitButton.setText("Πίσω");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jBtnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnDelete)
                                .addGap(67, 67, 67)
                                .addComponent(ExitButton))
                            .addComponent(textField1))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExitButton, jBtnDelete, jBtnEdit, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jBtnEdit)
                    .addComponent(jBtnDelete)
                    .addComponent(ExitButton))
                .addGap(47, 47, 47))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        AdminFrame mainadmin = new AdminFrame();
        mainadmin.setLocationRelativeTo(null);
        mainadmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        selected = jTable1.getSelectedRow();
        tempStore = storeList.get(selected);


        if (selected >= 0) {
            
      // ΠΡΟΣΟΡΙΝΆ ΜΟΝΟ ΓΙΑ ΤΕΣΤ !!!!!!!!!!!!!     
      textField1.setText("Γραμμή : " + selected + "   Εγγραφή πίνακα"
      + " καταστημάτων : " + tempStore.getStoreId());
/*
            
            if (tempStore.getPurchaseList().size() >0 || tempStore.getStoreProductList().size() >0) {
                int n = JOptionPane.showOptionDialog(rootPane,
                        "Υπάρχουν συνδέσεις με προϊόντα ή παραγγελίες\n"
                      + "με αυτό το κατάστημα. Θα χαθούν κι αυτές με \n"
                      + "τη διαγραφή του.   Είστε σίγουροι;"
                      , "    Προσοχή !!!", 2, 2, null, null, rootPane);
                if (n == 0) {

                    if (tempStore.getStoreProductList().size() >0) {
                        for (StoreProduct sp : tempStore.getStoreProductList()) {
                            StoreProduct temp = em.merge(sp);
                            em.remove(temp);
                        }
                    }
                    if (tempStore.getPurchaseList().size() >0) {
                        for (Purchase pu : tempStore.getPurchaseList()) {
                            pu.setStoreId(deleteStore); 
                            em.persist(pu);
                        }
                    }
                storeList.remove(selected);
                Store temp = em.merge(tempStore);
                em.remove(temp);
                em.getTransaction().begin();
                em.getTransaction().commit();
    
                }
            }
            else {
                int m = JOptionPane.showOptionDialog(rootPane,
                        "Το κατάστημα θα διαγραφεί μόνιμα \n"
                      + "από τη βάση δεδομένων \n"
                      + "   Είστε σίγουροι;"
                      , "    Προσοχή !!!", 2, 2, null, null, rootPane);
                if (m == 0) {
                    storeList.remove(selected);
                    Store temp = em.merge(tempStore);
                    em.remove(temp);
                    em.getTransaction().begin();
                    em.getTransaction().commit();
                }
            }

  */          
     /*       Store s = storeList.get(jTable1.convertRowIndexToModel(selected));
            for (StoreProduct sp : s.getStoreProductList()) {
                em.remove(sp);
            }*/
          //  storeList.remove(selected);
           // em.remove(selected);
        }
   /*     
        boolean ok;
        ok = true;
        int s = jTable1.getSelectedRow();
        if (s >= 0) {
            Customer c = list1.get(jTable1.convertRowIndexToModel(s));
            for (Vehicle v : c.getVehicleList()) {
                if ((!v.getCardId().getCollectionList().isEmpty()) || (!v.getCardId().getPaymentList().isEmpty())) {
                    ok = false;
                    break;
        }  }
            if (ok) {
                for (Vehicle v: c.getVehicleList()){
                    em.remove(v);
                }
                list1.remove(c);
                em.remove(c);
            } else {
                Utils.showMessage(this, String.format(Utils.msgCustomerCantBeDeleted, c.getFName(), c.getLName()), Utils.msgDialogTitle, JOptionPane.WARNING_MESSAGE);
            }
            checkControls();  }  */
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        
        
    }//GEN-LAST:event_jBtnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.persistence.EntityManager WebMarketPUEntityManager0;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<model.Store> storeList;
    private javax.persistence.Query storeQuery;
    private javax.swing.JTextField textField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}