package webmarket;

/**
 * @author Simos
 */

import model.Customer;

public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */

    Customer logedUser;
    
    public UserProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserPasswordButton = new javax.swing.JButton();
        UserEditProfileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserChecksButton = new javax.swing.JButton();
        logedUserText1 = new javax.swing.JTextField();
        logedUserText2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WebMarket - Διαχείριση Προφίλ");

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(0, 51, 204));
        ExitButton.setText("Επιστροφή");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Επιλέξτε εργασία");

        UserPasswordButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserPasswordButton.setText("Αλλαγή κωδικού");
        UserPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPasswordButtonActionPerformed(evt);
            }
        });

        UserEditProfileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserEditProfileButton.setText("Επεξεργασία Προφίλ");
        UserEditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEditProfileButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Έχετε συνδεθεί ως :");

        UserChecksButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserChecksButton.setText("Προβολή δωροεπιταγών");
        UserChecksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserChecksButtonActionPerformed(evt);
            }
        });

        logedUserText1.setEnabled(false);
        logedUserText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logedUserText1ActionPerformed(evt);
            }
        });

        logedUserText2.setEnabled(false);
        logedUserText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logedUserText2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logedUserText1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(logedUserText2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(UserPasswordButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserEditProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserChecksButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logedUserText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logedUserText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(UserEditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(UserPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(UserChecksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        UserFrame mainuser = new UserFrame();
        mainuser.setLogedUser(logedUser);
        mainuser.setLocationRelativeTo(null);
        mainuser.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void UserPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPasswordButtonActionPerformed
        UserPassword userpassword = new UserPassword();
        userpassword.setLogedUser(logedUser);
        userpassword.setLocationRelativeTo(null);
        userpassword.setVisible(true);
        dispose();
    }//GEN-LAST:event_UserPasswordButtonActionPerformed

    private void UserEditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEditProfileButtonActionPerformed
        UserEditProfile usereditprofile = new UserEditProfile();
        usereditprofile.setLogedUser(logedUser); 
        usereditprofile.setLocationRelativeTo(null);
        usereditprofile.setVisible(true);
        dispose();
    }//GEN-LAST:event_UserEditProfileButtonActionPerformed

    private void UserChecksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserChecksButtonActionPerformed
        UserChecks userchecks = new UserChecks(logedUser);
        userchecks.setLocationRelativeTo(null);
        userchecks.setVisible(true);
        dispose();
    }//GEN-LAST:event_UserChecksButtonActionPerformed

    private void logedUserText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logedUserText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logedUserText1ActionPerformed

    private void logedUserText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logedUserText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logedUserText2ActionPerformed

    public void setLogedUser (Customer logedUser){
        this.logedUser = logedUser;
        logedUserText1.setText(logedUser.getFirstName());
        logedUserText2.setText(logedUser.getLastName());
    }

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton UserChecksButton;
    private javax.swing.JButton UserEditProfileButton;
    private javax.swing.JButton UserPasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField logedUserText1;
    private javax.swing.JTextField logedUserText2;
    // End of variables declaration//GEN-END:variables
}
